'use client';

import { Bar, BarChart, CartesianGrid, XAxis, YAxis, Legend } from 'recharts';
import { ChartWrapper, ChartTooltipFrame } from '@/components/charts/chart-wrapper';
import type { PromoData } from '@/lib/types';
import { useMemo } from 'react';

const chartConfig = {
  '% discount': { label: '% Discount', color: 'hsl(var(--chart-1))' },
  'BOGO': { label: 'BOGO', color: 'hsl(var(--chart-2))' },
  'cashback': { label: 'Cashback', color: 'hsl(var(--chart-3))' },
  'bundle': { label: 'Bundle', color: 'hsl(var(--chart-4))' },
  'volume_offer': { label: 'Volume Offer', color: 'hsl(var(--chart-5))' },
};

export function OfferPerformanceChart({ data }: { data: PromoData[] }) {
  const chartData = useMemo(() => {
    const byProduct = data.reduce((acc: any, item) => {
        if (!item.promo_flag) return acc;
        if (!acc[item.product]) {
            acc[item.product] = { product: item.product };
        }
        if (!acc[item.product][item.promo_type]) {
            acc[item.product][item.promo_type] = 0;
        }
        acc[item.product][item.promo_type] += item.incremental_sales;
        return acc;
    }, {});
    return Object.values(byProduct);
  }, [data]);

  return (
    <ChartWrapper
      title="Offer Performance Comparison"
      description="Breakdown of incremental sales generated by each offer type, per product."
      chartConfig={chartConfig}
    >
      <BarChart data={chartData} layout="vertical" stackOffset="expand" margin={{ left: 20, right: 20, top: 10 }}>
        <CartesianGrid horizontal={false} />
        <XAxis type="number" tickFormatter={(value) => `${value * 100}%`} />
        <YAxis dataKey="product" type="category" width={80} />
        <Legend />
        <ChartTooltipFrame />
        {Object.keys(chartConfig).map(key => (
            <Bar key={key} dataKey={key} stackId="a" fill={`var(--color-${key})`} />
        ))}
      </BarChart>
    </ChartWrapper>
  );
}
